version: "3.7"
services:

  #Laravel App
  app:
    build:
      args:
        user: andres
        uid: 501
      context: ./
      dockerfile: Dockerfile
    image: poas-backend
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/

  #MariaDB Service
  rdb:
    image: mariadb:10.5.12
    command: --sql_mode=""
    user: mysql
    volumes:
      - rdb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default
      MYSQL_USER: default
      MYSQL_PASSWORD: default
    ports:
        - 3306:3306

volumes:
  rdb: